---
kind: ImageStream
apiVersion: v1
metadata:
  name: galleon-wildfly-builder
spec:
  tags:
  - name: latest
    annotations:
      description: galleon-wildfly-builder image
      iconClass: icon-jboss
      tags: java,widlfly,galleon
      version: 'latest'
    from:
      kind: DockerImage
      name: "quay.io/jfdenise/galleon-wildfly-builder:latest"