---
kind: ImageStream
apiVersion: v1
metadata:
  name: wildfly-runtime-dependencies-image
spec:
  tags:
  - name: latest
    annotations:
      description: wildfly-runtime-dependencies-image image
      iconClass: icon-jboss
      tags: java,widlfly,galleon
      version: 'latest'
    from:
      kind: DockerImage
      name: "quay.io/jfdenise/wildfly-runtime-dependencies-image:latest"