apiVersion: v1
kind: Template
metadata:
  name: wildfly-galleon-s2i-server-builder
  annotations:
    iconClass: icon-wildfly
    openshift.io/display-name: Galleon S2I WildFly builder
    openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/long-description: Build a WildFly server image using galleon.
    description: Build a WildFly server image using galleon.
  message: Builds created.
labels:
  template: wildfly-galleon-s2i-server-builder
parameters:
- name: SERVER_NAME
  description: The server name. This name is assigned to the built image.
  displayName: WildFly Server Image Name
  required: true
  value: my-server
- name: IMAGE_VERSION
  description: WildFly version to use (latest, full, 16.0.0.Final)
  displayName: WildFly version
  required: true
  value: latest
- name: GALLEON_GIT_REPO
  description: The Galleon server description git repository
  displayName: Galleon server description git repository
  required: true
  value: https://github.com/jfdenise/s2i-wildfly
- name: GALLEON_GIT_CONTEXT_DIR
  description: The Galleon server description git repository sub directory
  displayName: Galleon server description git repository sub directory
  required: false
  value: 17.0/galleon/cloud-profile-all-ds
- name: GALLEON_GIT_BRANCH
  description: The Galleon server description git branch
  displayName: Galleon server description git branch
  required: true
  value: master
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${SERVER_NAME}
    name: ${SERVER_NAME}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${SERVER_NAME}-artifacts
    name: ${SERVER_NAME}-artifacts
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${SERVER_NAME}
    name: ${SERVER_NAME}-artifacts
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${SERVER_NAME}-artifacts:latest
    runPolicy: Serial
    source:
      git:
        ref: ${GALLEON_GIT_BRANCH}
        uri: ${GALLEON_GIT_REPO}
      contextDir: ${GALLEON_GIT_CONTEXT_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: galleon-wildfly-builder:${IMAGE_VERSION}
        env:
          - name: "GALLEON_BUILD"
            value: "true"
      type: Source
    triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: secret101
      type: Generic
    - github:
      secret: secret101
    type: GitHub
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${SERVER_NAME}
    name: ${SERVER_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${SERVER_NAME}:latest
    source:
      dockerfile: |-
        FROM wildfly-runtime-dependencies-image:${IMAGE_VERSION}
        COPY /wildfly /opt/jboss/wildfly
        RUN chown -R 1001:0 /opt/jboss/wildfly && chmod -R ug+rwX /opt/jboss/wildfly
        # We should set the USER, When copying in app image, should use
        # --chown=1001:0 but docker version in minishift doesn't support it.
        # USER 1001
        EXPOSE 8080 9090
        CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
      images:
        - from: 
            kind: ImageStreamTag
            name: ${SERVER_NAME}-artifacts:latest
          paths: 
          - sourcePath: /output/wildfly
            destinationDir: "."
    strategy:
      dockerStrategy:
        from:
          kind: "ImageStreamTag"
          name: "wildfly-runtime-dependencies-image:${IMAGE_VERSION}"
      type: Docker
    triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: ${SERVER_NAME}-artifacts:latest
    - type: ConfigChange
    