---
kind: ImageStream
apiVersion: v1
metadata:
  name: taskrs
spec:
  tags:
  - name: latest
    annotations:
      description: taskrs image
      iconClass: icon-jboss
      tags: java,widlfly,galleon
      version: 'latest'
    from:
      kind: DockerImage
      name: "quay.io/jfdenise/taskrs-app:latest"